### ISSUE TITLE
Waterline-Sequel 0.5.0 dependency

### ISSUE THREAD

**Issue by cope** [lucianmachado/sails-oracle-database#4]
Hey @lucianmachado,

Can we remove the waterline-sequel 0.5.0 from the dependencies and use the latest version of it?

We have submitted a fix that is supposed to go into the 0.6.5 and with this hard dependency on 0.5.0, our fix will not be available.

**Comment by lucianmachado** [comment]
Hey @cope,

I think isn't a good idea to use the latest version of waterline-sequel because we need these PR's: [#17](https://github.com/balderdashy/waterline-sequel/pull/17), [#67](https://github.com/balderdashy/waterline-sequel/pull/67).

I noticed that the waterline-sequel is going to be replaced for waterline-sql-builder, so I think the best approach is migrate to waterline-sql-builder instead waterline-sequel...

**Comment by cope** [comment]
Ok, so then I will submit my waterline-sequel PR to your fork and then see what happens with waterline-sql-builder down the line...

Is that OK?

**Comment by cope** [comment]
Hi @lucianmachado,

I created the pull request for your fork of waterline-sequel: https://github.com/lucianmachado/waterline-sequel/pull/1

Please take a look and approve if it is OK :)

**Comment by lucianmachado** [comment]
@cope I'll check asap, thanks!
